services:
  backend:
    build: ./backend
    ports: 
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      - DB_HOST=db
      - DB_PORT=${MYSQL_INTERNAL_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_ROOT_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
          
  db:
    build: ./db
    ports: 
      - '${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}'
    environment:
      - MYSQL_PORT=${MYSQL_INTERNAL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "minimal_user", -pminimal_password]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

