# Use the official MySQL image as a base image
FROM mysql:latest

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=root_password

ENV MYSQl_DATABASE=recipe
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin

# Expose the MySQL port
EXPOSE 3306

